PARAMS:
  BATCH_SIZE: 8
  EPOCH: 1500
  N_SAMPLE: 1
  INPUT_FRAME: 4
  OUTPUT_FRAME: 6
  COVERAGE: 0.5
  CROP_SIZE: 256
  PARSER:
    FUNCTION: Nimrod_parser
    PARAMS:
      RAIN_TH: 0.01
      RAIN2DBZ: True
      MIN_VALUE: -9
  NORMALIZER:
    FUNCTION: min_max_normalizer
    PARAMS:
      MIN_VALUE: -9
      MAX_VALUE: 60
GENERATOR:
  MODEL: 
    FUNCTION: DGMRGenerator
    PARAMS:
  LOSS:
    FUNCTION: PixelWiseRegularizer
    PARAMS:
      LAMBDA: 20
      MIN_VALUE: 0.2
      MAX_VALUE: 1.5
  OPTIMIZER:
    FUNCTION: Adam
    PARAMS:
      LR: 0.0005
      BETAS: [0., 0.999]
  SCHEDULER:
    FUNCTION: 
    PARAMS:
DISCRIMINATOR:
  ITER: 2
  MODEL:
    FUNCTION: DGMRDiscriminators
    PARAMS:
      N_FRAME: 8
      CROP_SIZE: 128
  LOSS:
    FUNCTION: HingeLoss
    PARAMS:
      MARGIN: 1.
      LABEL_SMOOTHING: False
  OPTIMIZER:
    FUNCTION: Adam
    PARAMS:
      LR: 0.0002
      BETAS: [0., 0.999]
  SCHEDULER:
    FUNCTION:
    PARAMS:
EVALUATION:
  THRESHOLDS: [5, 10, 20, 30]
  POOLING_SCALES: [1, 4, 16]
TRAIN:
  VAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
VAL:
  BATCH_SIZE: 16
TEST:
  BATCH_SIZE: 1
DATALOADER:
  NUM_WORKERS: 32
  PIN_MEMORY: True
SETTINGS:
  IMPORT_CKPT_PATH: 
  NUM_GPUS: 1
  RNG_SEED: 0
  DATA_PATH: ["/home/yihan/yh/research/Nimrod/Nimrod_2019.dat", "/home/yihan/yh/research/Nimrod/Nimrod_2020.dat"]
  DATA_TYPE: int16
  DATA_SHAPE: [[105120, 512, 512], [105408, 512, 512]]
  RAIN_RECORD_PATH:
TENSORBOARD:
  SAVE_DIR: /home/yihan/yh
  VERSION: DGMR