PARAMS:
  BATCH_SIZE: int
  EPOCH: int
  N_SAMPLE: int
  INPUT_FRAME: int
  OUTPUT_FRAME: int
  COVERAGE: float
  CROP_SIZE: int
  PARSER:
    FUNCTION: parser_function
    PARAMS:
      ARG1:
      ARG2:
      ARG3:
  NORMALIZER: normalizer_function
    FUNCTION: 
    PARAMS:
      ARG1:
      ARG2:
GENERATOR:
  MODEL: 
    FUNCTION: DGMRGenerator
    PARAMS:
  LOSS:
    FUNCTION: PixelWiseRegularizer
    PARAMS:
      LAMBDA: 20
      MIN_VALUE: 0.2
      MAX_VALUE: 1.5
  OPTIMIZER:
    FUNCTION: Adam
    PARAMS:
      LR: 0.0005
      MOMENTUM: 0.9
      BETA: [0., 0.999]
  SCHEDULER:
    FUNCTION: 
    PARAMS:
DISCRIMINATOR:
  ITER: 2
  MODEL:
    FUNCTION: DGMRDiscriminators
    PARAMS:
      N_FRAME: 8
      CROP_SIZE: 128
  LOSS:
    FUNCTION: HingeLoss
    PARAMS:
      MARGIN: 1.
      LABEL_SMOOTHING: False
  OPTIMIZER:
    FUNCTION: Adam
    PARAMS:
      LR: 0.0002
      MOMENTUM: 0.9
      BETA: [0., 0.999]
  SCHEDULER:
    FUNCTION:
    PARAMS:
EVALUATION:
  THRESHOLDS: [5, 10, 20, 30]
  POOLING_SCALES: [1, 4, 16]
TRAIN:
  VAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
VAL:
  BATCH_SIZE: 16
TEST:
  BATCH_SIZE: 1
DATALOADER:
  NUM_WORKERS: 32
  PIN_MEMORY: True
SETTINGS:
  IMPORT_CKPT_PATH: 
  NUM_GPUS: 1
  RNG_SEED: 0
  DATA_PATH: /home/yihan/yh/research/Nimrod/Nimrod_2016.dat
  DATA_TYPE: int16
  DATA_SHAPE: (288*366, 512, 512)
  RAIN_RECORD_PATH:
TENSORBOARD:
  SAVE_DIR: /home/yihan/yh
  VERSION: EVAL